site_name: Py Return Success or Error
repo_url: https://github.com/pwlimaverde/py-return-success-or-error
repo_name: py-return-success-or-error
edit_uri: tree/main/docs

theme:
  name: material
  language: pt-BR
  logo: assets/logo.png
  favicon: assets/logo.png

nav:
  - Início: index.md
  - Referência de API:
      - Core: api/core.md
      - Errors: api/errors.md
      - Parameters: api/parameters.md
      - DataSources: api/datasources.md
      - Repositories: api/repositories.md
      - Usecases: api/usecases.md

markdown_extensions:
  - attr_list
  - admonition
  - codehilite
  - toc:
      permalink: true

extra_css:
  - stylesheets/custom.css

plugins:
  - mkdocstrings:
      handlers:
        python:
          paths:
            - src
          options:
            docstring_style: google
            show_root_heading: true
            show_source: true
